### ISSUE TITLE
登录时扫描二维码没有反应

### ISSUE THREAD

**Issue by hummersyk** [InfpPointPlus/Raptor#17]
用阿里云盘APP扫描登录时显示的二维码，没有任何反应，整合版和独立版都试过了都一样，请问是什么情况？

**Comment by InfpPointPlus** [comment]
> 用阿里云盘APP扫描登录时显示的二维码，没有任何反应，整合版和独立版都试过了都一样，请问是什么情况？

查看一下位于程序同级目录的 **Raptor.log** 文件中的内容，看看是否有错误。

**Comment by hummersyk** [comment]
> > 用阿里云盘APP扫描登录时显示的二维码，没有任何反应，整合版和独立版都试过了都一样，请问是什么情况？
> 
> 查看一下位于程序同级目录的 **Raptor.log** 文件中的内容，看看是否有错误。

[Raptor.log](https://github.com/InfpPointPlus/Raptor/files/14355500/Raptor.log)

**Comment by InfpPointPlus** [comment]
> > 日志中没有错误，接口响应正常。扫描以后再移动端确认登录，然后程序登录窗体会自动关闭。您方便提供一下 gif 图像嘛
> 
> 我不知道怎么提供GIF图像...... 
> 电脑端每次点击“去登录”，显示的二维码会刷新，然后点手机阿里云盘APP右上角的扫描，这么扫都没有任何反应，电脑端就一直显示“等待扫描”；我把手机端退出账号重新登录，再扫描，还是没有反应。

这样啊，那您尝试切换一下亮色主题（在设置- UI）再试一下呢。或者尝试调节手机摄像头的距离以及角度等

**Comment by hummersyk** [comment]
> 这样啊，那您尝试切换一下亮色主题（在设置- UI）再试一下呢。或者尝试调节手机摄像头的距离以及角度等

哈哈，亮色主题一下就扫进去了，看来是我手机的灵敏度太差了。
