### ISSUE TITLE
登录成功但无法访问文件目录

### ISSUE THREAD

**Issue by bingsunny0730** [InfpPointPlus/Raptor#8]
使用Standalone版本在主机和虚拟机上均会出现如下图的服务器错误信息，而Integrated版本却显示正常，是因为缺少相关组件么？！
![sshot-8897123361](https://github.com/InfpPointPlus/Raptor/assets/131505889/3aa3edb9-2d5e-4b7e-bb91-73b493a1d429)

**Comment by InfpPointPlus** [comment]
请在移动端查看是否已经超出最大可用登录设备。

**Comment by bingsunny0730** [comment]
懂了，确实不能一号多登录不同版本
